app/routes/main.py
from flask import Blueprint, render_template, make_response
from app.routes.utils.utils import logout
from app.routes.utils.session import check_logged_in_redirect
from app.routes.utils.cache import disable_caching, redirect,url_for
from flask import redirect, url_for, make_response, render_template

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    response = check_logged_in_redirect()
    if response:
        return response

    return redirect(url_for('login.login'))


@main_bp.route('/logout', methods=['POST'])
def logout_view():
    return logout()

app/templates/dashboard/admin/activitylog.html
{% extends 'dashboard/admin/layout.html' %}

{% block title %} Activity Logs | TimeGuard {% endblock %}

{% block header_title %}Activity Logs{% endblock %}

{% block content %}
    <div class="w-full h-full p-6">
        <div class="mb-4 flex justify-between items-center">
            <a href="{{ url_for('activitylog.download_csv', sort_by=sort_by, order=order) }}" 
            class="bg-green-500 text-black py-4 px-8 rounded border border-black hover:bg-green-700" 
            style="background-color: #eeeee4; font-size: 1.25rem; color: black;">
             <img src="{{ url_for('static', filename='images/icons/csv.svg') }}" alt="Download CSV" class="inline h-8 w-8 mr-2"> Download CSV
            </a>
            <div class="relative w-1/3">
                <input type="text" id="search-bar" placeholder="Search activities..." class="block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" />
            </div>
        </div>
    
    <div class="bg-[#eeeee4] p-6 rounded-lg shadow-md w-full max-w-full mb-8 relative">
        <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-[#eeeee4]">
                <tr>
                    <th class="px-6 py-3 text-left text-lg font-medium text-black uppercase tracking-wider">
                        <a href="{{ url_for('activitylog.activitylog', page=page, sort_by='activity_timestamp', order='asc' if sort_by != 'activity_timestamp' or order == 'desc' else 'desc') }}">
                            Timestamp
                            {% if sort_by == 'activity_timestamp' %}
                                {% if order == 'asc' %}
                                    ▲
                                {% else %}
                                    ▼
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th class="px-6 py-3 text-left text-lg font-medium text-black uppercase tracking-wider">
                        <a href="{{ url_for('activitylog.activitylog', page=page, sort_by='activity_type', order='asc' if sort_by != 'activity_type' or order == 'desc' else 'desc') }}">
                            Activity Type
                            {% if sort_by == 'activity_type' %}
                                {% if order == 'asc' %}
                                    ▲
                                {% else %}
                                    ▼
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th class="px-6 py-3 text-left text-lg font-medium text-black uppercase tracking-wider">
                        <a href="{{ url_for('activitylog.activitylog', page=page, sort_by='account_type', order='asc' if sort_by != 'account_type' or order == 'desc' else 'desc') }}">
                            Account Type
                            {% if sort_by == 'account_type' %}
                                {% if order == 'asc' %}
                                    ▲
                                {% else %}
                                    ▼
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th class="px-6 py-3 text-left text-lg font-medium text-black uppercase tracking-wider">
                        Employee Name
                    </th>
                    <th class="px-6 py-3 text-left text-lg font-medium text-black uppercase tracking-wider">
                        Employee ID
                    </th>
                </tr>
            </thead>
            <tbody class="bg-[#eeeee4] divide-y divide-gray-300">
                {% for record in records %}
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap text-lg text-black">{{ record[5] }}</td> 
                        <td class="px-6 py-4 whitespace-nowrap text-lg text-black">{{ record[4] }}</td> 
                        <td class="px-6 py-4 whitespace-nowrap text-lg text-black">{{ record[3] }}</td> 
                        <td class="px-6 py-4 whitespace-nowrap text-lg text-black">{{ record[0] }} {{ record[1] }}</td> 
                        <td class="px-6 py-4 whitespace-nowrap text-lg text-black">{{ record[2] }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Pagination -->
        <div class="flex justify-center mt-4">
            <nav class="relative z-0 inline-flex shadow-lg -space-x-px" aria-label="Pagination">
                {% if page > 1 %}
                    <a href="{{ url_for('activitylog.activitylog', page=1, sort_by=sort_by, order=order) }}" class="relative inline-flex items-center px-4 py-3 border border-gray-400 text-base font-medium text-white bg-indigo-600 rounded-full hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition ease-in-out duration-300">
                        <i class="fas fa-angle-double-left"></i>
                    </a>
                {% endif %}
                
                {% set start_page = page - 2 %}
                {% set end_page = page + 2 %}
                
                {% if start_page < 1 %}
                    {% set start_page = 1 %}
                {% endif %}
                
                {% if end_page > total_pages %}
                    {% set end_page = total_pages %}
                {% endif %}
                
                {% for p in range(start_page, end_page + 1) %}
                    <a href="{{ url_for('activitylog.activitylog', page=p, sort_by=sort_by, order=order) }}" class="relative inline-flex items-center px-4 py-3 border border-gray-400 text-base font-medium {{ 'bg-indigo-600' if p == page else 'bg-gray-300' }} rounded-full text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition ease-in-out duration-300">
                        {{ p }}
                    </a>
                {% endfor %}
                
                {% if page < total_pages %}
                    <a href="{{ url_for('activitylog.activitylog', page=total_pages, sort_by=sort_by, order=order) }}" class="relative inline-flex items-center px-4 py-3 border border-gray-400 text-base font-medium text-white bg-indigo-600 rounded-full hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition ease-in-out duration-300">
                        <i class="fas fa-angle-double-right"></i>
                    </a>
                {% endif %}
            </nav>
        </div>

    </div>

    </div>

    <script>
    document.getElementById('search-bar').addEventListener('input', function() {
        const query = this.value.toLowerCase();
        const rows = document.querySelectorAll('tbody tr');

        rows.forEach(row => {
            const cells = row.querySelectorAll('td');
            let match = false;

            cells.forEach(cell => {
                if (cell.textContent.toLowerCase().includes(query)) {
                    match = true;
                }
            });

            row.style.display = match ? '' : 'none';
        });
    });
    </script>
    
{% endblock %}

app/templates/dashboard/admin/admin_dashboard.html
{% extends 'dashboard/admin/layout.html' %}

{% block title %}Dashboard | TimeGuard {% endblock %}

{% block header_title %}Data Analysis{% endblock %}

{% block content %}
    
<div class="">
    <!-- Statistics Section -->
    <div class="flex flex-wrap -mx-2 mb-8">
        <div class="w-full md:w-1/4 px-2 mb-4">
            <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-md border border-black h-full flex flex-col justify-between">
                <h2 class="text-lg font-semibold mb-2">Total Users</h2>
                <p class="text-3xl font-bold">{{ total_users }}</p>
            </div>
        </div>
        <!-- <div class="w-full md:w-1/4 px-2 mb-4">
            <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-md border border-black h-full flex flex-col justify-between">
                <h2 class="text-lg font-semibold mb-2">Users with No Vehicles</h2>
                <p class="text-3xl font-bold">{{ users_with_no_vehicles }}</p>
            </div>
        </div> -->
    
        <!-- <div class="w-full md:w-1/4 px-2 mb-4">
            <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-md border border-black h-full flex flex-col justify-between">
                <h2 class="text-lg font-semibold mb-2">Total Number of RFID Tags</h2>
                <p class="text-3xl font-bold">{{ total_rfid_tags }}</p>
            </div>
        </div> -->
        
        <!-- <div class="w-full md:w-1/4 px-2 mb-4">
            <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-md border border-black h-full flex flex-col justify-between">
                <h2 class="text-lg font-semibold mb-2">Total Registered RFID Tags</h2>
                <p class="text-3xl font-bold">{{ registered_rfid_count }}</p>
            </div>
        </div> -->
    </div>
    
    <div class="mt-8">
        <div class="flex flex-wrap -mx-2 mb-8">
            <div class="w-full md:w-1/3 px-2 mb-4 md:mb-0">
                <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-lg h-full border border-black">
                    <h3 class="text-xl font-semibold mb-2">Time-In and Time-Out Comparison</h3>
                    <canvas id="timeInOutChart" class="w-full h-64"></canvas>
                    <div id="timeInOutData"
                         data-labels="{{ time_in_time_out_data['labels']|join(', ') }}"
                         data-timein="{{ time_in_time_out_data['timein']|join(', ') }}"
                         data-timeout="{{ time_in_time_out_data['timeout']|join(', ') }}">
                    </div>
                </div>
            </div>
    
            <div class="w-full md:w-1/3 px-2 mb-4 md:mb-0">
                <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-lg h-full border border-black">
                    <h3 class="text-xl font-semibold mb-2">Peak Hours of Vehicle Entries</h3>
                    <canvas id="peakHoursChart" class="w-full h-64"></canvas>
                    <div id="peakHoursData"
                         data-labels="{{ peak_hours_data['labels']|join(', ') }}"
                         data-data="{{ peak_hours_data['data']|join(', ') }}">
                    </div>
                </div>
            </div> 
    
            <div class="w-full md:w-1/3 px-2 mb-4 md:mb-0">
                <div style="background-color: #eeeee4; font-size: 1.25rem;" class="p-6 rounded-lg shadow-lg h-full border border-black">
                    <h3 class="text-xl font-semibold mb-2">User Registration by Week</h3>
                    <canvas id="userregistration" class="w-full h-64"></canvas>
                    <div id="userRegistrationData"
                         data-labels="{{ user_registration_data['labels']|join(', ') }}"
                         data-data="{{ user_registration_data['data']|join(', ') }}">
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>

<script src="{{ url_for('static', filename='js/timeinout-comparison.js') }}"></script>
<script src="{{ url_for('static', filename='js/vehicleChart.js') }}"></script>
<script src="{{ url_for('static', filename='js/durationofstay.js') }}"></script>
<script src="{{ url_for('static', filename='js/user_registered_weekly.js') }}"></script>
<script src="{{ url_for('static', filename='js/mostactivedays.js') }}"></script>
<script src="{{ url_for('static', filename='js/peakhours.js') }}"></script>
<script src="{{ url_for('static', filename='js/library/chart.min.js') }}"></script>

{% endblock %}

app/templates/dashboard/admin/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}Admin Dashboard | TimeGuard {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='/images/logo.png') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <!-- <link href="{{ url_for('static', filename='css/auth-login-register.css') }}" rel="stylesheet"> -->

    <style>
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }

        .animate-spin {
            animation: spin 0.5s linear infinite; 
        }
    </style>
</head>
<body class="relative bg-cover bg-center min-h-screen" style="background-color: #eeeee4; color: black;">

    <!-- Background Overlay -->
    <div class="absolute inset-0 bg-black opacity-65"></div>

<!-- Main Layout Structure -->
<div class="relative min-h-screen bg-opacity-30 backdrop-blur-md flex flex-col">
    <!-- Header -->
    <header id="header" class="bg-blue-600 bg-opacity-100 p-6 flex items-center fixed top-0 left-64 w-full z-30 shadow-md bg-black/50 backdrop-blur-md transition-all duration-300" style="background-color: rgb(0, 0, 141);">
        <!-- Toggle Button for Desktop Sidebar -->
        <button id="sidebar-toggle" class="mr-4 focus:outline-none">
            <span class="iconify" data-icon="mdi:menu" data-inline="false" style="font-size: 2rem;"></span>
        </button>
        <!-- Logo and Title on the Left -->
        <div class="flex items-center space-x-3">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="logo" class="h-12">
            <span class="font-bold text-xl text-off-white custom-shadow">{% block header_title %}Dashboard{% endblock %}</span>
        </div>
        <!-- Hamburger Menu for Mobile -->
        <div class="sm:hidden ml-auto">
            <button id="menu-toggle" class="focus:outline-none">
                <span class="iconify" data-icon="mdi:menu" data-inline="false" style="font-size: 2rem;"></span>
            </button>
        </div>
    </header>

    <!-- Mobile Sidebar -->
    <aside id="mobile-menu" class="bg-white text-gray-800 fixed inset-y-0 left-0 transform -translate-x-full transition-transform sm:hidden w-64 z-20 mt-20 backdrop-blur-md bg-white/30" style="background-color: #eeeee4; color: black;">
        <div class="p-6 flex flex-col items-center mb-4">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" class="h-20 mb-2">
            <h1 class="text-xl font-bold mb-4 mt-4 text-center">TimeGuard</h1>
        </div>
        <nav class="p-6 space-y-6">
            <a href="{{ url_for('admin_dashboard.admin_dashboard') }}" class="block py-3 rounded hover:bg-gray-100">Data Analytics</a>
            <a href="{{ url_for('timeinout.timeinout') }}" class="block py-3 rounded hover:bg-gray-100">Time In / Time Out</a>
            <a href="{{ url_for('userlist.userlist') }}" class="block py-3 rounded hover:bg-gray-100">Users</a>
            
            {% if super_admin_features %}
                <a href="{{ url_for('adminlist.adminlist') }}" class="block py-3 rounded hover:bg-gray-100">Manage Admins</a>
            {% endif %}
            
            <a href="{{ url_for('activitylog.activitylog') }}" class="block py-3 rounded hover:bg-gray-100">Activity Logs</a>

            <!-- <a href="{{ url_for('rfid.add_rfid') }}" class="block py-3 rounded hover:bg-gray-100">RFID</a> -->

            <button id="logout-button" class="block py-3 rounded hover:bg-gray-100">Logout</button>
        </nav>
    </aside>

    <!-- Desktop Sidebar -->
    <aside id="desktop-sidebar" class="w-64 bg-gray-800 bg-opacity-70 p-6 z-20 fixed top-0 left-0 h-full backdrop-blur-lg transition-transform duration-300" style="background-color: #eeeee4; color: black;">
        <div class="flex flex-col items-center mb-4">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" class="h-20 mb-2">
            <h1 class="text-xl font-bold mb-4 mt-4 text-center">TimeGuard</h1>
        </div>
        <nav class="space-y-4 flex flex-col justify-between h-full">
            <div class="space-y-4">
                <a href="{{ url_for('admin_dashboard.admin_dashboard') }}" class="block py-4 px-5 rounded hover:bg-gray-300">
                    <img src="{{ url_for('static', filename='images/icons/analytics.svg') }}" alt="Data Analytics" class="inline h-8 w-8 mr-2">Data Analytics
                </a>
                <a href="{{ url_for('timeinout.timeinout') }}" class="block py-4 px-5 rounded hover:bg-gray-300">
                    <img src="{{ url_for('static', filename='images/icons/timeinout.svg') }}" alt="Time In / Out" class="inline h-8 w-8 mr-2">Time Log
                </a>
                <a href="{{ url_for('userlist.userlist') }}" class="block py-4 px-5 rounded hover:bg-gray-300">
                    <img src="{{ url_for('static', filename='images/icons/users.svg') }}" alt="Registered Users" class="inline h-8 w-8 mr-2"> Users
                </a>
                
                {% if super_admin_features %}
                    <a href="{{ url_for('adminlist.adminlist') }}" class="block py-4 px-5 rounded hover:bg-gray-300">
                        <img src="{{ url_for('static', filename='images/icons/admin.svg') }}" alt="Manage Admins" class="inline h-8 w-8 mr-2"> Manage Admins
                    </a>
                {% endif %}
                
                <a href="{{ url_for('activitylog.activitylog') }}" class="block py-4 px-5 rounded hover:bg-gray-300">
                    <img src="{{ url_for('static', filename='images/icons/activitylogs.svg') }}" alt="Activity Logs" class="inline h-8 w-8 mr-2">Activity Logs
                </a>

                <!-- <a href="{{ url_for('rfid.add_rfid') }}" class="block py-4 px-5 rounded hover:bg-gray-300">
                    <img src="{{ url_for('static', filename='images/icons/rfid.svg') }}" alt="RFID" class="inline h-8 w-8 mr-2">RFID
                </a> -->

                <button id="logout-button-desktop" class="block py-4 px-5 rounded hover:bg-gray-300 mt-6">
                    <img src="{{ url_for('static', filename='images/icons/logout.svg') }}" alt="Logout" class="inline h-8 w-8 mr-2">Logout
                </button>
            </div>
        </nav>
    </aside>

    <!-- Main Content Area -->
    <div id="main-content" class="flex flex-1 mt-20 sm:ml-64 bg-black/10 p-10 backdrop-blur-md flex-grow transition-all duration-300" style="background-color: #eeeee4; color: black;">
        <div id="flashMessages" class="fixed top-0 left-1/2 transform -translate-x-1/2 m-4 z-50 opacity-100 transition-opacity duration-300">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="space-y-4">
                        {% for category, message in messages %}
                            <div class="p-3 mb-4 rounded 
                                {% if category == 'danger' %}
                                    bg-red-500 bg-opacity-80 text-white
                                {% elif category == 'success' %}
                                    bg-green-500 bg-opacity-80 text-white
                                {% elif category == 'info' %}
                                    bg-blue-500 bg-opacity-80 text-white
                                {% else %}
                                    bg-gray-500 bg-opacity-80 text-white
                                {% endif %}
                                {{ 'hidden' if not messages else 'block' }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
        </div>
        <div class="flex-1 flex flex-col justify-between items-center m-6 sm:m-8 md:m-10 lg:m-12">
            {% block content %}{% endblock %}
        </div>
    </div>

    <!-- Logout Confirmation Modal -->
    <div id="logout-modal" class="fixed inset-0 bg-gray-600 bg-opacity-50 z-40 hidden">
        <div class="flex items-center justify-center min-h-screen">
            <div class="bg-white p-6 rounded-lg shadow-lg w-96">
                <h2 class="text-lg font-semibold mb-4">Confirm Logout</h2>
                <p class="mb-4">Are you sure you want to logout?</p>
                <div class="flex justify-end space-x-4">
                    <form method="POST" action="{{ url_for('main.logout_view') }}">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700">Logout</button>
                    </form>
                    <button id="cancel-logout" class="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Loading Screen -->
    <div id="loading-screen" class="fixed inset-0 bg-transparent flex items-center justify-center z-50 hidden">
        <div class="flex items-center space-x-2">
            <div class="w-12 h-12 border-t-4 border-black border-solid rounded-full animate-spin"></div>
            <span class="text-black text-lg">Loading...</span>
        </div>
    </div>
</div>


<script>
    document.getElementById('sidebar-toggle').addEventListener('click', function() {
        const sidebar = document.getElementById('desktop-sidebar');
        const mainContent = document.getElementById('main-content');
        const header = document.getElementById('header');

        sidebar.classList.toggle('hidden');
        if (sidebar.classList.contains('hidden')) {
            sidebar.style.transform = 'translateX(-100%)'; // Animate sidebar out
            mainContent.classList.remove('sm:ml-64'); // Adjust padding when sidebar is hidden
            header.classList.remove('left-64'); // Adjust header when sidebar is hidden
        } else {
            sidebar.style.transform = 'translateX(0)'; // Animate sidebar in
            mainContent.classList.add('sm:ml-64'); // Restore padding when sidebar is visible
            header.classList.add('left-64'); // Adjust header when sidebar is visible
        }
    });
</script>

    <script>
        const menuToggle = document.getElementById('menu-toggle');
        const mobileMenu = document.getElementById('mobile-menu');

        menuToggle.addEventListener('click', function() {
            mobileMenu.classList.toggle('-translate-x-full');
        });

        const logoutButton = document.getElementById('logout-button');
        const logoutButtonDesktop = document.getElementById('logout-button-desktop');
        const logoutModal = document.getElementById('logout-modal');
        const cancelLogout = document.getElementById('cancel-logout');
        const loadingScreen = document.getElementById('loading-screen');

        function showLoading() {
            loadingScreen.classList.remove('hidden');
        }

        function hideLoading() {
            loadingScreen.classList.add('hidden');
        }

        document.querySelectorAll('aside nav a').forEach((element) => {
            element.addEventListener('click', function() {
                showLoading();
                setTimeout(() => { 
                    hideLoading();
                }, 1000);
            });
        });

        logoutButton.addEventListener('click', function() {
            logoutModal.classList.remove('hidden');
        });

        if (logoutButtonDesktop) {
            logoutButtonDesktop.addEventListener('click', function() {
                logoutModal.classList.remove('hidden');
            });
        }

        cancelLogout.addEventListener('click', function() {
            logoutModal.classList.add('hidden');
        });
    </script>

    <!-- Libraries -->
    <script src="{{ url_for('static', filename='js/library/chart.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/library/heatmap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/library/leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='js/library/leaflet-heat.js') }}"></script>
    <script src="{{ url_for('static', filename='js/library/iconify.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

app/templates/dashboard/admin/survey-admin.html
<!-- {% extends 'dashboard/admin/layout.html' %}

{% block title %}Survey | TimeGuard {% endblock %}

{% block header_title %}Survey{% endblock %}

{% block content %}


<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeKpbDdd6yVw_C8M4ZhkeO4cONEMA1JcuFZlLIotRSzZkqzHg/viewform?embedded=true" width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

{% endblock %} -->

app/templates/dashboard/admin/timeinout-weeklytrend.html
{% extends 'dashboard/admin/layout.html' %}

{% block title %}User Dashboard{% endblock %}

{% block content %}
    <!-- Tailwind CSS -->
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

    <!-- Chart.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <body class="bg-gray-100 min-h-screen flex flex-col" style="background-image: url('/static/images/CCV.jpg'); background-size: cover; background-position: center;">
        <!-- Fixed Header -->
        <header class="bg-blue-800 text-white p-4 flex items-center justify-between fixed top-0 left-0 w-full z-10 shadow-lg rounded-b-lg">
            <img src="{{ url_for('static', filename='images/CelcorCircle.png') }}" alt="logo" class="h-12"/>
            <h1 class="text-xl font-bold mx-auto">Weekly Entry/Exit Statistics</h1>
        </header>

        <!-- Centered Container with Chart -->
        <div class="flex-1 flex flex-col justify-center items-center mt-20 px-4">
            <!-- Chart Container -->
            <div class="bg-white p-6 rounded-lg shadow-md flex flex-col w-full max-w-3xl mb-8 relative">
                <h2 class="text-xl font-bold mb-4">Total Entry/Exit</h2>
                <canvas id="entryExitChart"></canvas>
            </div>
        </div>

        <script>
            const ctx = document.getElementById('entryExitChart').getContext('2d');
            const entryExitChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                    datasets: [{
                        label: 'This year',
                        data: [500, 1200, 1500, 800, 2000, 2500, 3000],
                        borderColor: 'black',
                        backgroundColor: 'rgba(0, 0, 0, 0.1)',
                        fill: true,
                        tension: 0.4
                    }, {
                        label: 'Last year',
                        data: [400, 1100, 1000, 700, 1900, 2200, 2800],
                        borderColor: 'lightblue',
                        backgroundColor: 'rgba(173, 216, 230, 0.2)',
                        fill: true,
                        tension: 0.4
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true,
                            max: 3000
                        }
                    },
                    plugins: {
                        legend: {
                            display: true,
                            labels: {
                                color: 'black'
                            }
                        }
                    }
                }
            });
        </script>
    </body>
{% endblock %}